# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=2000
HISTFILESIZE=2000
HISTIGNORE="pwd:clc:clear:ls:cd:mv:sudo"
HISTTIMEFORMAT="%F %T `whoami` "  

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

#颜色配置
#\033[0;30m：黑色   \033[1;30m：深灰色 \033[0;31m：红色
#\033[1;31m：浅红色 \033[0;32m：绿色   \033[1;32m：浅绿色
#\033[0;33m：棕色   \033[1;33m：黄色   \033[0;34m：蓝色
#\033[1;34m：浅蓝色 \033[0;35m：粉红   \033[1;35m：浅粉色
#\033[0;36m：青色   \033[1;36m：浅青色 \033[0;37m：浅灰色
#\033[1;37m：白色   \033[00m: 恢复默认颜色   
if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;33m\]\W\[\033[01;32m\] 🐄  \[\033[00m\]'
    #PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;33m\]\W\[\033[01;32m\]\$ \[\033[00m\]'
    #PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;33m\]\W\[\033[00m\]\$ '
    #PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\W\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \W\a\]$PS1"
    #PS1="\[\e[01;32m\]\u@\h: \W]\$"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'
	alias rm="bash /usr/local/shibin/Rm"
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'


# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

##########################各种环境配置#########################################
#自建脚本存放环境配置
export Shibin="/usr/local/shibin"
export PATH="$PATH:$Shibin"

#Python语言环境变量配置和alias
#export P2_env="$HOME/.virtualenvs"
#export PATH="$PATH:$P2_env"
#alias python='python3'

#Java语言环境变量配置
#export JAVA_HOME="/usr/local/jdk-15.0.1"
#export PATH="$PATH:$JAVA_HOME/bin"

#Go语言环境变量配置
#export GOROOT="/usr/local/go"
#export GOPATH="/home/shieber/practice/Go"
#export PATH="$PATH:$GOPATH:$GOPATH/bin:$GOROOT/bin"
#export GOPROXY="https://goproxy.cn,direct"
#export GO111MODULE=auto
#CGO_ENABLED=1
#alias bee="/home/shieber/practice/Go/bin/bee"

#Rust语言环境变量配置
#export RUSTPATH="$HOME/.cargo/bin"
#export PATH="$PATH:$RUSTPATH"

#Cheat高亮配置
export CHEATCOLORS=true

######命令别名###########
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias lf='ls | grep -v ^d' #只列出文件
alias ld='ls -d */'        #只列出目录
alias ls='ls -lh --group-directories-first --color=auto' #将文件和目录分开列出
alias vi='vim'
alias svi='sudo vi'
alias clc='clear'
alias vlc='/usr/local/shibin/vlc'
alias www='python3 -m SimpleHTTPServer 9090' 
alias Man='tldr' 
alias sudo='sudo env PATH=$PATH'
alias pingb='ping -c 4 www.baidu.com'
alias battery="upower -i `upower -e | grep 'BAT'`"
alias Install='sudo apt install' 
alias Update='sudo apt update; sudo apt upgrade -y' 
#alias k='kubectl'
#alias pdf='evince' 
#alias web='source ~/env/website/bin/activate'
#alias bok='source ~/env/bookmarks/bin/activate'
#alias tensor='source ~/env/tensor/bin/activate'
#alias stop='deactivate'
#alias mysql='mysql -u shieber -p'
#alias notebook='jupyter notebook'
#alias sqlstart="sudo service mysql start"
#alias sqlstop="sudo service mysql stop"
#alias sqllogin="mysql -u shieber -p"
#alias sqlsulogin="mysql -u root -p"
